# Generated by Django 4.2.16 on 2024-09-22 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='Jehanabad', max_length=15)),
                ('area_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stock_in_kg', models.IntegerField(default=0)),
                ('one_bora_in_kg', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.company')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('disc_percent', models.DecimalField(decimal_places=2, default=2, max_digits=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.company')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bora', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('purchase_order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='inventory.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bora', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Dukandaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('address', models.CharField(default='', max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.area')),
            ],
        ),
        migrations.CreateModel(
            name='DailyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_time', models.DateTimeField(auto_now_add=True)),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dukandaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dukandaar', to='inventory.dukandaar')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='inventory.company')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='dukandaar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.dukandaar'),
        ),
    ]
