# Generated by Django 4.2.16 on 2024-09-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_dailycollection_pending_amount_as_of_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='one_bora_in_kg',
            field=models.IntegerField(default=1),
        ),
    ]
